name: "Lint - action"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    - name: Install dependencies
      run: |
        python -m pip install .[test]
    - name: Run lint
      run: |
        npm install -g pyright
        make code-style code-lint
    - name: Run test
      run: make test
